- name: Ensure Docker network exists
  community.docker.docker_network:
    name: "{{ network_name }}"
  tags: frontend

- name: Run Frontend container
  community.docker.docker_container:
    name: "{{ frontend_container }}"
    image: "{{ frontend_image }}"
    ports:
      - "{{ frontend_port }}"
    networks:
      - name: "{{ network_name }}"
    env:
      REACT_APP_API_URL: "http://backend_cont:5000"
      HOST: "0.0.0.0"
    restart_policy: always
    state: started
  tags: frontend
