---

- name: Ensure Docker network exists # it ensure the network exists before running the frontend container
  community.docker.docker_network:
    name: "{{ network_name }}"
  tags: frontend

- name: Run Frontend container # this will run my frontend container
  community.docker.docker_container:
    name: "{{ frontend_container }}"
    image: "{{ frontend_image }}"
    ports:
      - "{{ frontend_port }}"
    networks:
      - name: "{{ network_name }}"
    env:
      REACT_APP_API_URL: "http://{{ backend_container }}:{{ backend_internal_port | default('5000') }}" # this sets the backend URL for the frontend to communicate with the backend container
    restart_policy: always
    state: started
  tags: frontend
