# Frntend Deployment 
apiVersion: apps/v1
kind: Deployment # this my type of resource
metadata:
  name: frontend          
  labels:
    app: frontend            
spec:
  replicas: 1    # i frontend pod for now
  selector:
    matchLabels:
      app: frontend    # this matches the lebel i gave it
  template:
    metadata:
      
        app: frontend
    spec:
      containers:
        - name: frontend
          image: lenoxisindu/frontend:v1.0.2   # my frontend image
          ports:
            - containerPort: 3000     # the port exposed inside the container
          env:
            - name: REACT_APP_API_URL          # this will route to my backend for comunication
              value: "http://backend-service:5000/api"
