apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo         # matches the label in my mongo Deployment
  ports:
    - protocol: TCP
      port: 27017     
      targetPort: 27017
  type: ClusterIP      
