---
- name: Check if MongoDB container is running
  community.docker.docker_container_info:
    name: "{{ mongo_container }}"
  register: mongo_status
  failed_when: mongo_status is failed
  changed_when: false

- name: Wait for MongoDB container to be ready
  community.docker.docker_container_info:
    name: "{{ mongo_container }}"
  register: mongo_health
  retries: 10
  delay: 5
  until: mongo_health.container.State.Running is defined and mongo_health.container.State.Running
  changed_when: false

- name: Ensure backend directory exists
  file:
    path: "{{ project_path }}/backend"
    state: directory
    owner: vagrant
    group: vagrant
    mode: "0755"

- name: Ensure backend .env file exists
  copy:
    dest: "{{ project_path }}/backend/.env"
    content: |
      MONGODB_URI=mongodb://mongo_db:27017/yolomy
      PORT=5000
    owner: vagrant
    group: vagrant
    mode: "0644"
  when: not lookup('ansible.builtin.file', project_path + '/backend/.env', errors='ignore')

- name: Run Backend container
  community.docker.docker_container:
    name: "{{ backend_container }}"
    image: "{{ backend_image }}"
    env_file: "{{ project_path }}/backend/.env"
    ports:
      - "{{ backend_port }}"
    networks:
      - name: "{{ network_name }}"
    restart_policy: always
    state: started
  tags: backend
