---
- name: Run MongoDB container
  community.docker.docker_container:
    name: "{{ mongo_container }}"
    image: "{{ mongo_image }}" # this i have already defined it in the vars task
    ports:
      - "{{ mongo_port }}"
    volumes:
      - "{{ volume_name }}:/data/db"
    networks:
      - name: "{{ network_name }}"
    restart_policy: always
  tags: mongo # mongo tag to identify this task in my main playbook
