---
- name: Deploy E-commerce Web Application
  hosts: all
  become: true
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Clone project repository from GitHub
      tags: git
      git:
        repo: "{{ github_repo }}"
        dest: "{{ project_path }}"
        version: master
        force: yes

   
  roles:
    - role: docker     # this will Install and verifies Docker + Compose
      tags: docker

    - role: mongo      # MongoDB container
      tags: mongo

    - role: backend    # backend container
      tags: backend

    - role: frontend   # frontend container
      tags: frontend
